// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.PayHistory.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HistoryOperationViewModel
    {
        /// <summary>
        /// Initializes a new instance of the HistoryOperationViewModel class.
        /// </summary>
        public HistoryOperationViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HistoryOperationViewModel class.
        /// </summary>
        /// <param name="type">Possible values include: 'None', 'Recharge',
        /// 'OutgoingInvoicePayment', 'IncomingInvoicePayment',
        /// 'OutgoingExchange', 'IncomingExchange', 'Withdrawal',
        /// 'CashOut'</param>
        public HistoryOperationViewModel(HistoryOperationType type, System.DateTime createdOn, double amount, string id = default(string), string oppositeMerchantId = default(string), string assetId = default(string), string invoiceId = default(string))
        {
            Id = id;
            Type = type;
            OppositeMerchantId = oppositeMerchantId;
            CreatedOn = createdOn;
            Amount = amount;
            AssetId = assetId;
            InvoiceId = invoiceId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'None', 'Recharge',
        /// 'OutgoingInvoicePayment', 'IncomingInvoicePayment',
        /// 'OutgoingExchange', 'IncomingExchange', 'Withdrawal', 'CashOut'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public HistoryOperationType Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OppositeMerchantId")]
        public string OppositeMerchantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedOn")]
        public System.DateTime CreatedOn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvoiceId")]
        public string InvoiceId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
